# NAME: MUHAMMAD AMAR BUSTARI BIN YUSLAN

# MATRIC NO: U2100793

# QUESTION 1

In [23]:
def dydt(t,y):
    return(-2*y*t)
 # Python program to implement Runge Kutta method   # Finds value of y for a given t using step size h
# and initial value y0 at t0.


def rungekutta(t0, y0, t, h):
    
        # Count number of iterations using step size or
    # step height

    
    n = int((t-t0/h))
   # Iterate for number of iterations
  
    y = y0
    
    for i in range(1,n+1):
            # Apply Runge Kutta Formulas to find next value of y

        k1 = h*dydt(t0, y)
        k2 = h*dydt(t0 + 0.5 * h,y + 0.5 * k1)
        k3 = h*dydt(t0 + 0.5 * h,y + 0.5 * k2)
        k4 = h*dydt(t0 + h, y +k3)
  # Update next value of y
      
        y=y + (1.0/6.0)*(k1 + 2 * k2 + 2 * k3 + k4)
     # Update next value of t
   
        t0 = t0 +h
    return y
#driver method
t0 = 0
y = 2
t = 0
h = 0.2
print('The value of y at t is:' , rungekutta(t0, y, t, h))
    

The value of y at t is: 2


In [35]:
from matplotlib import plyplot as plt

def dydt(t,y):
    return(-2*y*t)
 # Python program to implement Runge Kutta method   # Finds value of y for a given t using step size h
# and initial value y0 at t0.


def rungekutta(t0, y0, t, h):
    
        # Count number of iterations using step size or
    # step height

    
    n = int((t-t0/h))
   # Iterate for number of iterations
  
    y = y0
    
    for i in range(1,n+1):
            # Apply Runge Kutta Formulas to find next value of y

        k1 = h*dydt(t0, y)
        k2 = h*dydt(t0 + 0.5 * h,y + 0.5 * k1)
        k3 = h*dydt(t0 + 0.5 * h,y + 0.5 * k2)
        k4 = h*dydt(t0 + h, y +k3)
  # Update next value of y
      
        y=y + (1.0/6.0)*(k1 + 2 * k2 + 2 * k3 + k4)
     # Update next value of t
   
        t0 = t0 +h
    return y
#driver method
t0 = 0
y = 2
t = 0
h = 0.2
return dydt

plt.figure()
plt.plot(t,y)

plt.title('y(t) vs t')
plt.xlabel('t values')
plt.ylabel('y(t) values')

ImportError: cannot import name 'plyplot' from 'matplotlib' (C:\Users\Acer\anaconda3\Lib\site-packages\matplotlib\__init__.py)

# QUESTION 2

In [2]:
import numpy as np
import scipy as sc 

A = np.array([[2,4,6],[5,3,2],[7,8,9]])

print(A)

[[2 4 6]
 [5 3 2]
 [7 8 9]]


In [4]:
B = np.array([[18],[13],[20]])

print(B)

[[18]
 [13]
 [20]]


In [11]:
C = np.linalg.solve(A,B)

print(C)

[[ 12.83333333]
 [-29.16666667]
 [ 18.16666667]]


# Question 3

In [48]:
import requests

api_url = 'https://api.open-meteo.com/v1/forecast?latitude=2.5&longitude=112.5&hourly=temperature_2m&timezone=Asia%2FSingapore&forecast_days=1'
forecast_data = response.json()

forecastdays = {['forecast'] for days in forecast_data}

forecast_days = input('Enter the number of days')

days = forecast_data.get(forecastdays.title())

if days is range(1,16):
    print('the range of days should be less than 16 days')
else:
    print(f"{forecast_days} is not found in the data.")

TypeError: unhashable type: 'list'